# Generated by Django 3.2.3 on 2021-05-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_auto_20210525_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Bottom Name', max_length=250)),
                ('design_image', models.ImageField(upload_to='uploads/Bottom/')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productdesign',
            name='pents',
            field=models.ManyToManyField(to='constructor.Pants'),
        ),
    ]
